### ISSUE TITLE
Packages for multiple patch versions of Scala

### ISSUE THREAD

**Issue by sideeffffect** [cb372/scala-typed-holes#11]
Version `0.0.4` is published for [`2.13.0-M5`, `2.12.8` and `2.11.12`](https://mvnrepository.com/artifact/com.github.cb372/scala-typed-holes).
Should it be just `2.12`, `2.11` (and `2.13.0-M5`)?

Is it really intentional that the package is published only for `2.12.8`, but not `2.12.7` for example?

**Comment by cb372** [comment]
This is intentional. See #6 for details.

We could cross-publish for older patch versions such as 2.12.7, but I imagine the kind of person who uses this plugin is likely to use the latest version of the compiler.

**Comment by sideeffffect** [comment]
OK, let's publish it for multiple Scala versions
I took [`splain`](https://mvnrepository.com/artifact/io.tryp/splain) as an example
