### ISSUE TITLE
Type hole is not recognised in function literals

### ISSUE THREAD

**Issue by SimY4** [cb372/scala-typed-holes#17]
In this example:
```
object test {
  def ex1(i: => Int): Int = ??? // <- works fine
  def ex2(i: Int => Int): Int = ??? // <- works fine

  ex1 { ??? } // <- doesn't work
  ex2 { _ => ??? } // <- doesn't work
}
```
Is this expected? I'm using scala 2.12.8

**Comment by cb372** [comment]
Thanks for the report.

This is probably a pattern of tree that the plugin doesn't currently match. Shouldn't be too hard to add a case for it. I'll take a look.
