### ISSUE TITLE
Global plugin

### ISSUE THREAD

**Issue by TimWSpence** [cb372/scala-typed-holes#36]
Is it possible to use this as a global plugin (so that you don't need to commit changes to your build.sbt if you want to use this but other people working on the same project don't necessarily).

Sorry, this is probably not an issue with the plugin but rather my lack of knowledge of sbt!

I tried adding it to my `~/.sbt/1.0/plugins.sbt` and then adding `-P:typed-holes:log-level:error` to `.sbtopts` (which can be git-ignored) but this gave me the error
```
[error] Expected ';'
[error] -P:typed-holes:log-level:error
[error]
```
when I launched sbt

**Comment by cb372** [comment]
Don't forget, scala-typed-holes is a compiler plugin, not an sbt plugin!

This should do what you want:

```
// ~/.sbt/1.0/holes.sbt
addCompilerPlugin("com.github.cb372" % "scala-typed-holes" % "0.1.4" cross CrossVersion.full)
scalacOptions += "-P:typed-holes:log-level:error"
```

**Comment by TimWSpence** [comment]
Ah, that is indeed the requisite sbt knowledge I was missing. Thanks so much! And thanks so much for such an awesome plugin 🙂
